# fly.toml app configuration file generated for bsky-hirogaru-bluesky on 2024-03-05T23:45:00+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bsky-hirogaru-bluesky'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
